"""
Theme system for QuizGO with multiple aesthetic options.
"""

THEMES = {
    "stranger_things": {
        "name": "🌌 Stranger Things",
        "background": "#0B0B0F",
        "window_bg": "#1A1A2E", 
        "panel_bg": "#16213E",
        "foreground": "#E94560",
        "primary": "#FF073A",
        "secondary": "#00D4FF",
        "accent": "#39FF14",
        "purple": "#8A2BE2",
        "highlight": "#FFD700",
        "success": "#00FF41",
        "error": "#FF073A",
        "button_bg": "#2E2E48",
        "button_border": "#E94560",
        "shadow": "#000000",
        "font_family": "'Courier New', 'Consolas', monospace",
        "title_font": "'Impact', 'Arial Black', sans-serif",
        "font_size": "14px",
        "title_size": "20px",
        "grid_texture": "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(233, 69, 96, 0.1) 2px, rgba(233, 69, 96, 0.1) 4px)",
        "scan_lines": "repeating-linear-gradient(90deg, transparent, transparent 2px, rgba(0, 212, 255, 0.03) 2px, rgba(0, 212, 255, 0.03) 4px)",
    },
    
    "retro_student": {
        "name": "📟 Retro Student",
        "background": "#C0C0C0",
        "window_bg": "#F0F0F0",
        "panel_bg": "#E0E0E0", 
        "foreground": "#000080",
        "primary": "#0000FF",
        "secondary": "#008080",
        "accent": "#800080",
        "purple": "#800080",
        "highlight": "#FFFF00",
        "success": "#008000",
        "error": "#FF0000",
        "button_bg": "#D4D0C8",
        "button_border": "#808080",
        "shadow": "#404040",
        "font_family": "'MS Sans Serif', 'Tahoma', sans-serif",
        "title_font": "'MS Sans Serif', 'Tahoma', sans-serif",
        "font_size": "12px",
        "title_size": "14px",
        "grid_texture": "none",
        "scan_lines": "none",
    },
    
    "notebook_scribble": {
        "name": "📚 Notebook Scribble",
        "background": "#FFFEF7",
        "window_bg": "#FFFFFF",
        "panel_bg": "#F8F8FF",
        "foreground": "#2F4F4F",
        "primary": "#FF69B4",
        "secondary": "#87CEEB",
        "accent": "#98FB98",
        "purple": "#DDA0DD",
        "highlight": "#FFFF99",
        "success": "#90EE90",
        "error": "#FFB6C1",
        "button_bg": "#FFF8DC",
        "button_border": "#4682B4",
        "shadow": "#D3D3D3",
        "font_family": "'Comic Sans MS', 'Trebuchet MS', sans-serif",
        "title_font": "'Comic Sans MS', 'Trebuchet MS', sans-serif", 
        "font_size": "14px",
        "title_size": "18px",
        "grid_texture": "repeating-linear-gradient(0deg, transparent 0px, transparent 24px, #E0E0E0 24px, #E0E0E0 25px)",
        "scan_lines": "none",
    },
    
    "pastel_teen": {
        "name": "🌸 Pastel Teen Core",
        "background": "#FFE4E1",
        "window_bg": "#F0F8FF",
        "panel_bg": "#E6E6FA",
        "foreground": "#4B0082",
        "primary": "#FF69B4",
        "secondary": "#87CEEB",
        "accent": "#98FB98",
        "purple": "#DDA0DD",
        "highlight": "#FFFF99",
        "success": "#90EE90",
        "error": "#FFB6C1",
        "button_bg": "#F5F5DC",
        "button_border": "#DA70D6",
        "shadow": "#D8BFD8",
        "font_family": "'Comic Sans MS', 'Trebuchet MS', sans-serif",
        "title_font": "'Comic Sans MS', 'Trebuchet MS', sans-serif",
        "font_size": "14px", 
        "title_size": "18px",
        "grid_texture": "none",
        "scan_lines": "none",
    },
    
    "gameboy": {
        "name": "🎮 GameBoy Study",
        "background": "#9BBB58",
        "window_bg": "#8BAC0F",
        "panel_bg": "#306230",
        "foreground": "#0F380F",
        "primary": "#0F380F",
        "secondary": "#306230",
        "accent": "#8BAC0F",
        "purple": "#0F380F",
        "highlight": "#9BBB58",
        "success": "#8BAC0F",
        "error": "#306230",
        "button_bg": "#9BBB58",
        "button_border": "#0F380F",
        "shadow": "#306230",
        "font_family": "'Courier New', monospace",
        "title_font": "'Courier New', monospace",
        "font_size": "12px",
        "title_size": "16px",
        "grid_texture": "repeating-conic-gradient(#9BBB58 0% 25%, #8BAC0F 0% 50%) 50% / 4px 4px",
        "scan_lines": "none",
    },
    
    "mall_goth": {
        "name": "🖤 Mall Goth Mode",
        "background": "#1C1C1C",
        "window_bg": "#2D2D30",
        "panel_bg": "#3E3E42",
        "foreground": "#E6E6E6",
        "primary": "#9932CC",
        "secondary": "#8B008B",
        "accent": "#FF1493",
        "purple": "#4B0082",
        "highlight": "#DA70D6",
        "success": "#9370DB",
        "error": "#DC143C",
        "button_bg": "#36393F",
        "button_border": "#9932CC",
        "shadow": "#000000",
        "font_family": "'Georgia', 'Times New Roman', serif",
        "title_font": "'Georgia', 'Times New Roman', serif",
        "font_size": "14px",
        "title_size": "18px",
        "grid_texture": "none",
        "scan_lines": "none",
    },
    
    "arcade_neon": {
        "name": "🕹 Arcade Neon",
        "background": "#000000",
        "window_bg": "#0A0A0A",
        "panel_bg": "#1A1A1A",
        "foreground": "#00FFFF",
        "primary": "#FF0080",
        "secondary": "#00FF00",
        "accent": "#FFFF00",
        "purple": "#8000FF",
        "highlight": "#FF8000",
        "success": "#00FF80",
        "error": "#FF4000",
        "button_bg": "#202020",
        "button_border": "#00FFFF",
        "shadow": "#404040",
        "font_family": "'Orbitron', 'Courier New', monospace",
        "title_font": "'Orbitron', 'Courier New', monospace",
        "font_size": "14px",
        "title_size": "18px",
        "grid_texture": "repeating-linear-gradient(0deg, transparent, transparent 10px, rgba(0, 255, 255, 0.1) 10px, rgba(0, 255, 255, 0.1) 11px)",
        "scan_lines": "repeating-linear-gradient(90deg, transparent, transparent 2px, rgba(255, 0, 128, 0.05) 2px, rgba(255, 0, 128, 0.05) 4px)",
    },
    
    "minimal_stationery": {
        "name": "✏️ Minimal Stationery",
        "background": "#F5F5DC",
        "window_bg": "#FFFEF0",
        "panel_bg": "#FAF0E6",
        "foreground": "#2F4F4F",
        "primary": "#4682B4",
        "secondary": "#708090",
        "accent": "#5F9EA0",
        "purple": "#6A5ACD",
        "highlight": "#F0E68C",
        "success": "#6B8E23",
        "error": "#CD5C5C",
        "button_bg": "#F8F8FF",
        "button_border": "#696969",
        "shadow": "#C0C0C0",
        "font_family": "'Georgia', 'Times New Roman', serif",
        "title_font": "'Georgia', 'Times New Roman', serif",
        "font_size": "14px",
        "title_size": "16px",
        "grid_texture": "none",
        "scan_lines": "none",
    }
}

# Default theme
CURRENT_THEME = "stranger_things"

def get_current_theme():
    return THEMES[CURRENT_THEME]

def set_theme(theme_name):
    global CURRENT_THEME
    if theme_name in THEMES:
        CURRENT_THEME = theme_name
        return True
    return False

def get_theme_list():
    return [(key, theme["name"]) for key, theme in THEMES.items()]